# This is a basic workflow to help you get started with Actions

name: Reddit Reader CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Run Kotlin Lint
      run: ./gradlew ktlintCheck
    
    - name: Run Android Lint
      run: ./gradlew lintDebug
    
    - name: Run Unit Tests
      run: ./gradlew test
      
    - name: Assemble Debug APK
      run: ./gradlew assembleDebug
    
    - name: "Run UI Tests"
      uses: reactivecircus/android-emulator-runner@v2.8.0
      with:
        api-level: 26
        script: ./gradlew connectedCheck
